### ISSUE TITLE
Add the source code for the website.

### ISSUE THREAD

**Issue by arpit9667** [Awesome-React-Modules/React-Dark-Website#1]

**Comment by BhuwanChandra** [comment]
@arpit9667 @yellowwoods12 I would like to work on this issue. please assign this to me.

**Comment by BhuwanChandra** [comment]
@arpit9667 please add difficulty tag and other related tags on the issue

**Comment by BhuwanChandra** [comment]
@arpit9667 @yellowwoods12 can you tell me which functionalities need to be implemented on the website?
like it should be a basic website to show the implementation of the react-dark library or also need to add getting started guide on the website.
