### ISSUE TITLE
Update the readme for the website

### ISSUE THREAD

**Issue by yellowwoods12** [Awesome-React-Modules/React-Dark-Website#2]

**Comment by Kuljeet-123** [comment]
@yellowwoods12  I would like to work on it as a part of GSSOC'20 participant.Please assign me this.

**Comment by yellowwoods12** [comment]
@Kuljeet-123 go ahead!

**Comment by Kuljeet-123** [comment]
@yellowwoods12 Please review it and tell me If I have to change something

**Comment by Kuljeet-123** [comment]
@yellowwoods12 please review my PR #3 and merge it.
